# .github/workflows/hola.yml
name: Hola GitHub Actions

# Evento que dispara la acci√≥n
on: push

jobs:
  ejemplo:
    runs-on: ubuntu-latest

    steps:
    - name: Decir Hola
      run: echo "Hola GitHub Actions"
