name: Ejecutar tests de Python automáticamente

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargando código del repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar pytest
        run: pip install pytest

      - name: Ejecutar pruebas
        run: pytest

